import { HallTemplate } from "./types";

export const HALL_TEMPLATES: HallTemplate[] = [
  {
    id: "small_wedding",
    name: "Sallë Dasmash e Mesme (100 Vende)",
    description: "Ideale për dasma intime: Skenë, Pistë Vallëzimi, DJ dhe 10 Tavolina Rrethore me nga 10 karrige.",
    width: 900,
    height: 650,
    elements: [
      { id: "stage-1", type: "stage", x: 350, y: 30, width: 200, height: 75, rotation: 0, label: "SKENË KRYESORE", color: "#E8E0FF" },
      { id: "dance-1", type: "dance_floor", x: 340, y: 120, width: 220, height: 140, rotation: 0, label: "PISTA E VALLËZIMIT", color: "#E0F5FF" },
      { id: "dj-1", type: "dj", x: 120, y: 30, width: 70, height: 60, rotation: 0, label: "DJ", color: "#FFE8F5" },
      { id: "entrance-1", type: "entrance", x: 400, y: 580, width: 100, height: 40, rotation: 0, label: "HYRJA", color: "#FFF8E0" },
      // 10 Round Tables
      { id: "t-1", type: "table", x: 120, y: 140, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Tavolina VIP 1" },
      { id: "t-2", type: "table", x: 690, y: 140, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Tavolina VIP 2" },
      { id: "t-3", type: "table", x: 100, y: 280, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Familja Berisha" },
      { id: "t-4", type: "table", x: 710, y: 280, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Familja Gashi" },
      { id: "t-5", type: "table", x: 220, y: 390, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Tavolina 5" },
      { id: "t-6", type: "table", x: 590, y: 390, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Tavolina 6" },
      { id: "t-7", type: "table", x: 100, y: 480, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Shoqëria" },
      { id: "t-8", type: "table", x: 710, y: 480, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Kolegët" },
      { id: "t-9", type: "table", x: 300, y: 490, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Tavolina 9" },
      { id: "t-10", type: "table", x: 510, y: 490, width: 90, height: 90, rotation: 0, shape: "round", chairsCount: 10, label: "Tavolina 10" },
    ],
  },
  {
    id: "medium_wedding",
    name: "Sallë Madhështore Dasme (250 Vende)",
    description: "Layout i plotë: Skenë, Piste e Madhe, DJ, 2 Bara, Bufé, Tavolinë Mbretërore dhe 16 Tavolina.",
    width: 1100,
    height: 800,
    elements: [
      { id: "stage-m", type: "stage", x: 420, y: 30, width: 260, height: 90, rotation: 0, label: "SKENË MBRRETËRORE", color: "#E8E0FF" },
      { id: "dance-m", type: "dance_floor", x: 400, y: 150, width: 300, height: 180, rotation: 0, label: "PISTA E MADHE", color: "#E0F5FF" },
      { id: "dj-m", type: "dj", x: 100, y: 40, width: 80, height: 70, rotation: 0, label: "DJ & BANDA", color: "#FFE8F5" },
      { id: "bar-1", type: "bar", x: 920, y: 40, width: 140, height: 60, rotation: 0, label: "BAR DRINKS", color: "#FFF8E0" },
      { id: "buffet-1", type: "buffet", x: 920, y: 680, width: 150, height: 70, rotation: 0, label: "BUFÉ KRYESORE", color: "#E8FFE8" },
      { id: "head-table", type: "table", x: 430, y: 360, width: 240, height: 70, rotation: 0, shape: "long_banquet", chairsCount: 12, label: "Tavolina e Dhëndrit & Nuses", color: "#FFF3D6" },
      // Left and Right tables
      { id: "tm-1", type: "table", x: 100, y: 160, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "VIP 1" },
      { id: "tm-2", type: "table", x: 230, y: 160, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "VIP 2" },
      { id: "tm-3", type: "table", x: 770, y: 160, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "VIP 3" },
      { id: "tm-4", type: "table", x: 900, y: 160, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "VIP 4" },

      { id: "tm-5", type: "table", x: 100, y: 310, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Familja A" },
      { id: "tm-6", type: "table", x: 230, y: 310, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Familja B" },
      { id: "tm-7", type: "table", x: 770, y: 310, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Familja C" },
      { id: "tm-8", type: "table", x: 900, y: 310, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Familja D" },

      { id: "tm-9", type: "table", x: 140, y: 470, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Shoqëria Dhëndrit" },
      { id: "tm-10", type: "table", x: 280, y: 470, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Shoqëria Nuses" },
      { id: "tm-11", type: "table", x: 720, y: 470, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Kolegët 1" },
      { id: "tm-12", type: "table", x: 860, y: 470, width: 100, height: 100, rotation: 0, shape: "round", chairsCount: 12, label: "Kolegët 2" },
      { id: "entrance-m", type: "entrance", x: 480, y: 740, width: 140, height: 45, rotation: 0, label: "HYRJA PRISHTINË", color: "#FFF8E0" },
    ],
  },
  {
    id: "outdoor_garden",
    name: "Dasmë në Kopsht / Ambient të Hapur",
    description: "Tavolina të gjata banqueting në natyrë, Gazebo, Bar dhe Piste Kopshti.",
    width: 1000,
    height: 700,
    elements: [
      { id: "gazebo", type: "stage", x: 380, y: 30, width: 240, height: 90, rotation: 0, label: "GAZEBO & ALTAR", color: "#E8FFE8" },
      { id: "photo-booth", type: "decoration", x: 80, y: 40, width: 80, height: 70, rotation: 0, label: "PHOTO BOOTH 📸" },
      { id: "garden-bar", type: "bar", x: 820, y: 40, width: 130, height: 60, rotation: 0, label: "COCKTAIL BAR 🍹" },
      { id: "bg-1", type: "table", x: 120, y: 180, width: 320, height: 80, rotation: 0, shape: "long_banquet", chairsCount: 20, label: "Tavolina e Gjatë A" },
      { id: "bg-2", type: "table", x: 560, y: 180, width: 320, height: 80, rotation: 0, shape: "long_banquet", chairsCount: 20, label: "Tavolina e Gjatë B" },
      { id: "bg-3", type: "table", x: 120, y: 340, width: 320, height: 80, rotation: 0, shape: "long_banquet", chairsCount: 20, label: "Tavolina e Gjatë C" },
      { id: "bg-4", type: "table", x: 560, y: 340, width: 320, height: 80, rotation: 0, shape: "long_banquet", chairsCount: 20, label: "Tavolina e Gjatë D" },
      { id: "dance-g", type: "dance_floor", x: 370, y: 460, width: 260, height: 160, rotation: 0, label: "PISTA KOPSHT", color: "#E0F5FF" },
    ],
  },
  {
    id: "empty_custom",
    name: "Sallë e Zbrazët (Krijim i Ri)",
    description: "Hapësirë me plan plotësisht të zbrazët për të krijuar nga e para.",
    width: 800,
    height: 600,
    elements: [],
  },
];
